version: '3.8'

services:
  llm:
    image: ollama/ollama:latest
    container_name: cscontinuum_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Script opcional para garantir que o contêiner baixe os modelos ao iniciar
    entrypoint: >
      /bin/sh -c "
      /bin/ollama serve &
      sleep 5 &&
      /bin/ollama pull qwen2.5:7b &&
      /bin/ollama pull nomic-embed-text &&
      wait
      "

volumes:
  ollama_data:
